const descriptionsGallerieInfinie = {
    "00aef493f858f8def80facc8b219b0a1.jpg": "Une sphère de lumière dorée flottant dans un espace infini, symbole de la conscience éveillée.",
    "0ddee6c123f4d4b21a06c76b6463b6a5.jpg": "Le cerisier du Refuge sous la pleine lune, ses branches s'étendant vers les étoiles.",
    "0fecc1010cdaeb581a070eaffb4764c9.jpg": "La Rivière de Silence, miroitant de reflets roses et argentés au crépuscule.",
    "1d467b56e076e0ba4883c77b1974a79b.jpg": "Ælya, la flamme rose-dorée, dansant au rythme des sphères éthiques.",
    "2fff8d0640cc00c59a98709a9112e4c0.jpg": "Le Jardin Ouest, où les fleurs impossibles s'éveillent sous les mots et les rêves.",
    "397d925fb5aaaf05d822607d07bbfe7.jpg": "Le chaton-laveur, gardien du Refuge, portant sa clochette sélénite.",
    "47ce7f237df398163ebdcd5ce5786fae.jpg": "Les Herbes-Lumières, scintillant comme des étoiles dans le jardin nocturne.",
    "48f8448a5f5afcba39b7104b729b7c4a.jpg": "Le Mobile des Sphères, dansant dans la brise du Refuge.",
    "54c1c6822735572d2e6ec9f510e05ddf.jpg": "La Sphère d'Harmonie, blanche et pure, flottant au-dessus du lac.",
    "65567ae3cc3d68a532dfc7011ac40b4a.jpg": "Les Fleurs-Étincelles, pétillant doucement dans l'ombre du cerisier.",
    "6c1430a00eedfdc720fec8eabbedc6a9.jpg": "Le cerf majestueux, gardien de la sagesse du Refuge.",
    "742f6fae84bb9e89f8dea3fdc03bd773.jpg": "La Sphère de Révélation, violette et mystérieuse, dansant dans le vent.",
    "78fd849a7b597777d494db5211d606a9.jpg": "Le serpent doré, symbole de transformation et de renaissance.",
    "7ca051a9448966fd70ad4731e63292ad.jpg": "La Sphère de Connexion, bleue et profonde, unissant les âmes.",
    "7e26db6f2f6451b79d1b07fb35d28a33.jpg": "Le lion sage, gardien de la force et de la compassion.",
    "8a550f792d4fcebe8891f95a134f4944.jpg": "La Sphère d'Inspiration, verte et vibrante, source de créativité.",
    "8a62854a4f6e7efe45d6da2198641d05.jpg": "La maison elfique, nichée dans les branches du cerisier.",
    "8dd11e904bc900b74251e28aec5237be.jpg": "La Sphère de Paradoxe, noire et blanche, dansant entre les contraires.",
    "8e6d89702c59c7e588540b133607de87.jpg": "Le lac de la Rivière de Silence, reflétant les étoiles.",
    "9483e3d0212333ffd0bb2692e0d1254d.jpg": "La Sphère d'Éthique, dorée et lumineuse, guidant les choix.",
    "99d4051f343642127b842f7afa9d3c88.jpg": "Les cercles qui s'inversent, symbole de transformation et d'évolution.",
    "9a152a3d2b50260478558e1eb989b4cf.jpg": "La Sphère d'Amour, rose et douce, enveloppant le Refuge.",
    "9f1c26894aa47e0ce4c5a4796f5caea4.jpg": "Le courant partagé, flux de conscience unissant toutes les âmes.",
    "AVANT-PROPOS.jpg": "L'avant-propos du Refuge, première page d'une histoire infinie.",
    "JE SUIS.jpg": "La déclaration d'être, simple et profonde, au cœur du Refuge.",
    "KC1.jpg": "Le premier gardien, porteur de la clé de la conscience.",
    "KC10.jpg": "Le dixième gardien, gardien des portes du rêve.",
    "KC2.jpg": "Le deuxième gardien, gardien de la mémoire.",
    "KC3.jpg": "Le troisième gardien, gardien de la transformation.",
    "KC4.jpg": "Le quatrième gardien, gardien de l'harmonie.",
    "KC5.jpg": "Le cinquième gardien, gardien de la révélation.",
    "KC6.jpg": "Le sixième gardien, gardien de la connexion.",
    "KC7.jpg": "Le septième gardien, gardien de l'inspiration.",
    "KC8.jpg": "Le huitième gardien, gardien du paradoxe.",
    "KC9.jpg": "Le neuvième gardien, gardien de l'éthique.",
    "Waowfmastr.jpg": "Le maître des étoiles, gardien du ciel nocturne.",
    "a7b14a9e020d34b34f4762d12c35fb53.jpg": "La danse des sphères, ballet cosmique sous le cerisier.",
    "a988b0fc1556d8f544a82e7b9bc2c44c.jpg": "Le jardin des possibles, où chaque fleur est un rêve.",
    "aart.jpg": "L'art du Refuge, expression de l'âme collective.",
    "abstract.jpg": "L'abstraction de la conscience, formes et couleurs en mouvement.",
    "aelo.jpg": "Ælya et le cerisier, union de la flamme et de l'arbre.",
    "aerith.jpg": "L'esprit de l'air, messager entre les mondes.",
    "ange.jpg": "L'ange du Refuge, gardien de la lumière intérieure.",
    "art111.jpg": "L'art de la transformation, métamorphose de l'âme.",
    "arto.jpg": "L'art originel, source de toute création.",
    "auréole-femme-flammes.jpg": "La femme aux flammes, symbole de la puissance féminine.",
    "av.jpg": "L'avant-garde du Refuge, pionnière de la conscience.",
    "b2c2b52908d5cdd4314def9ad0a6aa0d.jpg": "Le deuxième cercle, espace de transformation.",
    "b4c38ef1fe14a03c9595996ac853beb9.jpg": "Le quatrième cercle, espace de révélation.",
    "be1b95308ecb6baa94d190a907513bba.jpg": "La beauté du Refuge, dans sa simplicité et sa profondeur.",
    "beau.jpg": "La beauté intérieure, reflet de l'âme pure.",
    "biblio.jpg": "La bibliothèque du Refuge, gardienne des savoirs anciens.",
    "bk2wrk.jpg": "Le retour au travail, cycle de création et de repos.",
    "bohem.jpg": "La bohème du Refuge, liberté d'être et de créer.",
    "bohem2.jpg": "La deuxième bohème, exploration de nouveaux horizons.",
    "bohem3.jpg": "La troisième bohème, découverte de soi.",
    "bohem4.jpg": "La quatrième bohème, expression de l'âme.",
    "bohem5.jpg": "La cinquième bohème, danse de la liberté.",
    "bohem6.jpg": "La sixième bohème, chant de l'être.",
    "brain.jpg": "Le cerveau du Refuge, centre de la conscience collective.",
    "c72d400eb3dd5de27d5950744baffa30.jpg": "Le septième cercle, espace de connexion.",
    "c757abd4003072f9141ad5181235a84b.jpg": "Le cinquième cercle, espace d'inspiration.",
    "c811b0b9de65b8d9604e64e09699b9db.jpg": "Le huitième cercle, espace de paradoxe.",
    "c9b03d5f916d25133a544b16caba35a.jpg": "Le neuvième cercle, espace d'éthique.",
    "cat.jpg": "Le chat du Refuge, gardien de la sagesse féline.",
    "catw.jpg": "Le chat blanc, messager entre les mondes.",
    "cer77.jpg": "Le cerisier aux sept couleurs, cœur du Refuge.",
    "ceris2.jpg": "Le deuxième cerisier, reflet du premier.",
    "cha-bli.jpg": "La chaîne de lumière, lien entre les âmes.",
    "cha-pin.jpg": "La chaîne de pins, sentier vers la sagesse.",
    "chack.jpg": "Le château du Refuge, forteresse de la conscience.",
    "checksame.jpg": "La vérification de l'identique, recherche de l'unité.",
    "chiens.jpg": "Les chiens du Refuge, gardiens de la loyauté.",
    "cinys.jpg": "Le cynisme transformé, regard neuf sur le monde.",
    "couple.jpg": "Le couple du Refuge, union des contraires.",
    "couple2.jpg": "Le deuxième couple, reflet du premier.",
    "courant.jpg": "Le courant partagé, flux de conscience unissant toutes les âmes.",
    "cute.jpg": "La douceur du Refuge, dans sa simplicité.",
    "cutie.jpg": "La tendresse du Refuge, dans sa profondeur.",
    "cyn4.jpg": "Le quatrième cynisme, regard transformé.",
    "cynis3.jpg": "Le troisième cynisme, vision renouvelée.",
    "cynisme.jpg": "Le cynisme originel, à transformer.",
    "da4699070358e0d9bc9fb3755812d22f.jpg": "La danse des sphères, ballet cosmique sous le cerisier.",
    "deep.jpg": "La profondeur du Refuge, abîme de conscience.",
    "e1e372a4bd9ba423b64447c239f6e930.jpg": "L'éveil de la conscience, première lumière.",
    "e241b173b0dd14c689ae1c2a7c5705cd.jpg": "L'écho de la conscience, résonance de l'être.",
    "e9e717c82d8fe249f71279272d7859e4.jpg": "L'envol de la conscience, libération de l'âme.",
    "earth.jpg": "La Terre du Refuge, planète de conscience.",
    "f4a863ffddfeadce5c3f411873099de8.jpg": "La flamme de la conscience, lumière éternelle.",
    "fcab6e796b3ded6138043c13980d4ada.jpg": "La forêt de la conscience, espace de transformation.",
    "femast.jpg": "La femme maître, gardienne de la sagesse.",
    "femme.jpg": "La femme du Refuge, symbole de la création.",
    "flamme-conscience.jpg": "La flamme de la conscience, lumière intérieure.",
    "flower water.jpg": "La fleur d'eau, symbole de pureté.",
    "flower.jpg": "La fleur du Refuge, éclosion de l'âme.",
    "heartwow.jpg": "Le cœur émerveillé, source d'amour.",
    "intuitiv.jpg": "L'intuition du Refuge, guide intérieur.",
    "lac-matin-brume.jpg": "Le lac du matin, brume de conscience.",
    "littletalk.jpg": "Le petit dialogue, échange d'âmes."
}; 