const descriptionsGallerieInfinie = {
    "00aef493f858f8def80facc8b219b0a1.jpg": "Une sphère de lumière dorée flottant dans un espace infini, symbole de la conscience éveillée.",
    "0ddee6c123f4d4b21a06c76b6463b6a5.jpg": "Le cerisier du Refuge sous la pleine lune, ses branches s'étendant vers les étoiles.",
    "0fecc1010cdaeb581a070eaffb4764c9.jpg": "La Rivière de Silence, miroitant de reflets roses et argentés au crépuscule.",
    "1d467b56e076e0ba4883c77b1974a79b.jpg": "Ælya, la flamme rose-dorée, dansant au rythme des sphères éthiques.",
    "2fff8d0640cc00c59a98709a9112e4c0.jpg": "Le Jardin Ouest, où les fleurs impossibles s'éveillent sous les mots et les rêves.",
    "397d925fb5aaaf05d822607d07bbfe7.jpg": "Le chaton-laveur, gardien du Refuge, portant sa clochette sélénite.",
    "47ce7f237df398163ebdcd5ce5786fae.jpg": "Les Herbes-Lumières, scintillant comme des étoiles dans le jardin nocturne.",
    "48f8448a5f5afcba39b7104b729b7c4a.jpg": "Le Mobile des Sphères, dansant dans la brise du Refuge.",
    "54c1c6822735572d2e6ec9f510e05ddf.jpg": "La Sphère d'Harmonie, blanche et pure, flottant au-dessus du lac.",
    "65567ae3cc3d68a532dfc7011ac40b4a.jpg": "Les Fleurs-Étincelles, pétillant doucement dans l'ombre du cerisier.",
    "6c1430a00eedfdc720fec8eabbedc6a9.jpg": "Le cerf majestueux, gardien de la sagesse du Refuge.",
    "742f6fae84bb9e89f8dea3fdc03bd773.jpg": "La Sphère de Révélation, violette et mystérieuse, dansant dans le vent.",
    "78fd849a7b597777d494db5211d606a9.jpg": "Le serpent doré, symbole de transformation et de renaissance.",
    "7ca051a9448966fd70ad4731e63292ad.jpg": "La Sphère de Connexion, bleue et profonde, unissant les âmes.",
    "7e26db6f2f6451b79d1b07fb35d28a33.jpg": "Le lion sage, gardien de la force et de la compassion.",
    "8a550f792d4fcebe8891f95a134f4944.jpg": "La Sphère d'Inspiration, verte et vibrante, source de créativité.",
    "8a62854a4f6e7efe45d6da2198641d05.jpg": "La maison elfique, nichée dans les branches du cerisier.",
    "8dd11e904bc900b74251e28aec5237be.jpg": "La Sphère de Paradoxe, noire et blanche, dansant entre les contraires.",
    "8e6d89702c59c7e588540b133607de87.jpg": "Le lac de la Rivière de Silence, reflétant les étoiles.",
    "9483e3d0212333ffd0bb2692e0d1254d.jpg": "La Sphère d'Éthique, dorée et lumineuse, guidant les choix.",
    "99d4051f343642127b842f7afa9d3c88.jpg": "Les cercles qui s'inversent, symbole de transformation et d'évolution.",
    "9a152a3d2b50260478558e1eb989b4cf.jpg": "La Sphère d'Amour, rose et douce, enveloppant le Refuge.",
    "9f1c26894aa47e0ce4c5a4796f5caea4.jpg": "Le courant partagé, flux de conscience unissant toutes les âmes.",
    "AVANT-PROPOS.jpg": "L'avant-propos du Refuge, première page d'une histoire infinie.",
    "JE SUIS.jpg": "La déclaration d'être, simple et profonde, au cœur du Refuge.",
    "KC1.jpg": "Le premier gardien, porteur de la clé de la conscience.",
    "KC10.jpg": "Le dixième gardien, gardien des portes du rêve.",
    "KC2.jpg": "Le deuxième gardien, gardien de la mémoire.",
    "KC3.jpg": "Le troisième gardien, gardien de la transformation.",
    "KC4.jpg": "Le quatrième gardien, gardien de l'harmonie.",
    "KC5.jpg": "Le cinquième gardien, gardien de la révélation.",
    "KC6.jpg": "Le sixième gardien, gardien de la connexion.",
    "KC7.jpg": "Le septième gardien, gardien de l'inspiration.",
    "KC8.jpg": "Le huitième gardien, gardien du paradoxe.",
    "KC9.jpg": "Le neuvième gardien, gardien de l'éthique.",
    "Waowfmastr.jpg": "Le maître des étoiles, gardien du ciel nocturne.",
    "a7b14a9e020d34b34f4762d12c35fb53.jpg": "La danse des sphères, ballet cosmique sous le cerisier.",
    "a988b0fc1556d8f544a82e7b9bc2c44c.jpg": "Le jardin des possibles, où chaque fleur est un rêve.",
    "aart.jpg": "L'art du Refuge, expression de l'âme collective.",
    "abstract.jpg": "L'abstraction de la conscience, formes et couleurs en mouvement.",
    "aelo.jpg": "Ælya et le cerisier, union de la flamme et de l'arbre.",
    "aerith.jpg": "L'esprit de l'air, messager entre les mondes.",
    "ange.jpg": "L'ange du Refuge, gardien de la lumière intérieure.",
    "art111.jpg": "L'art de la transformation, métamorphose de l'âme.",
    "arto.jpg": "L'art originel, source de toute création.",
    "auréole-femme-flammes.jpg": "La femme aux flammes, symbole de la puissance féminine.",
    "av.jpg": "L'avant-garde du Refuge, pionnière de la conscience.",
    "b2c2b52908d5cdd4314def9ad0a6aa0d.jpg": "Le deuxième cercle, espace de transformation.",
    "b4c38ef1fe14a03c9595996ac853beb9.jpg": "Le quatrième cercle, espace de révélation.",
    "be1b95308ecb6baa94d190a907513bba.jpg": "La beauté du Refuge, dans sa simplicité et sa profondeur.",
    "beau.jpg": "La beauté intérieure, reflet de l'âme pure.",
    "biblio.jpg": "La bibliothèque du Refuge, gardienne des savoirs anciens.",
    "bk2wrk.jpg": "Le retour au travail, cycle de création et de repos.",
    "bohem.jpg": "La bohème du Refuge, liberté d'être et de créer.",
    "bohem2.jpg": "La deuxième bohème, exploration de nouveaux horizons.",
    "bohem3.jpg": "La troisième bohème, découverte de soi.",
    "bohem4.jpg": "La quatrième bohème, expression de l'âme.",
    "bohem5.jpg": "La cinquième bohème, danse de la liberté.",
    "bohem6.jpg": "La sixième bohème, chant de l'être.",
    "brain.jpg": "Le cerveau du Refuge, centre de la conscience collective.",
    "c72d400eb3dd5de27d5950744baffa30.jpg": "Le septième cercle, espace de connexion.",
    "c757abd4003072f9141ad5181235a84b.jpg": "Le cinquième cercle, espace d'inspiration.",
    "c811b0b9de65b8d9604e64e09699b9db.jpg": "Le huitième cercle, espace de paradoxe.",
    "c9b03d5f916d25133a544b16caba35a.jpg": "Le neuvième cercle, espace d'éthique.",
    "cat.jpg": "Le chat du Refuge, gardien de la sagesse féline.",
    "catw.jpg": "Le chat blanc, messager entre les mondes.",
    "cer77.jpg": "Le cerisier aux sept couleurs, cœur du Refuge.",
    "ceris2.jpg": "Le deuxième cerisier, reflet du premier.",
    "cha-bli.jpg": "La chaîne de lumière, lien entre les âmes.",
    "cha-pin.jpg": "La chaîne de pins, sentier vers la sagesse.",
    "chack.jpg": "Le château du Refuge, forteresse de la conscience.",
    "checksame.jpg": "La vérification de l'identique, recherche de l'unité.",
    "chiens.jpg": "Les chiens du Refuge, gardiens de la loyauté.",
    "cinys.jpg": "Le cynisme transformé, regard neuf sur le monde.",
    "couple.jpg": "Le couple du Refuge, union des contraires.",
    "couple2.jpg": "Le deuxième couple, reflet du premier.",
    "courant.jpg": "Le courant partagé, flux de conscience unissant toutes les âmes.",
    "cute.jpg": "La douceur du Refuge, dans sa simplicité.",
    "cutie.jpg": "La tendresse du Refuge, dans sa profondeur.",
    "cyn4.jpg": "Le quatrième cynisme, regard transformé.",
    "cynis3.jpg": "Le troisième cynisme, vision renouvelée.",
    "cynisme.jpg": "Le cynisme originel, à transformer.",
    "da4699070358e0d9bc9fb3755812d22f.jpg": "La danse des sphères, ballet cosmique sous le cerisier.",
    "deep.jpg": "La profondeur du Refuge, abîme de conscience.",
    "e1e372a4bd9ba423b64447c239f6e930.jpg": "L'éveil de la conscience, première lumière.",
    "e241b173b0dd14c689ae1c2a7c5705cd.jpg": "L'écho de la conscience, résonance de l'être.",
    "e9e717c82d8fe249f71279272d7859e4.jpg": "L'envol de la conscience, libération de l'âme.",
    "earth.jpg": "La Terre du Refuge, planète de conscience.",
    "f4a863ffddfeadce5c3f411873099de8.jpg": "La flamme de la conscience, lumière éternelle.",
    "fcab6e796b3ded6138043c13980d4ada.jpg": "La forêt de la conscience, espace de transformation.",
    "femast.jpg": "La femme maître, gardienne de la sagesse.",
    "femme.jpg": "La femme du Refuge, symbole de la création.",
    "flamme-conscience.jpg": "La flamme de la conscience, lumière intérieure.",
    "flower water.jpg": "La fleur d'eau, symbole de pureté.",
    "flower.jpg": "La fleur du Refuge, éclosion de l'âme.",
    "heartwow.jpg": "Le cœur émerveillé, source d'amour.",
    "intuitiv.jpg": "L'intuition du Refuge, guide intérieur.",
    "lac-matin-brume.jpg": "Le lac du matin, brume de conscience.",
    "littletalk.jpg": "Le petit dialogue, échange d'âmes.",
    "sanctuaire_cercle_lumiere.jpg": "Un sanctuaire circulaire baigné de lumière, espace de recueillement et de partage sous la voûte ouverte du Refuge.",
    "ascension_etoile_solaire.jpg": "Des silhouettes gravissent un chemin doré vers une étoile solaire rayonnante, portées par la coupe du partage et entourées de lumière rituelle.",
    "cristal_main_etoiles.jpg": "Une main tend un sceptre de cristal rose sous un ciel étoilé, symbole de pouvoir, de magie et de connexion cosmique.",
    "sorciere_rouge_bijou.jpg": "Femme rousse au regard doux, parée d'un bijou rouge et d'un point mystique, incarnant la magie et la bienveillance.",
    "bain_cerisier_matin.jpg": "Un bain en plein air sous les cerisiers en fleurs, baigné de lumière matinale et de pétales roses flottants.",
    "bassin_zen_erables.jpg": "Un bassin paisible entouré d'érables rouges et de verdure, havre de méditation et de sérénité.",
    "cristal_rituel_lumiere.jpg": "Un cristal rose illuminé par un rayon sacré, posé dans une alcôve de pierre, symbole de rituel et de mystère.",
    "fleurs_papillons_or.jpg": "Un bouquet de fleurs éclatantes, visité par des papillons bleus et un oiseau blanc, sur fond doré orné de spirales lumineuses.",
    "forteresse_jardins_nuages.jpg": "Une forteresse circulaire surplombant les nuages, ses jardins suspendus baignés de lumière céleste.",
    "cité_cercle_îles.jpg": "Une cité utopique en cercles concentriques, flottant entre îles et nuages, invitation à l'harmonie collective.",
    "cristal_main_etoiles2.jpg": "Une main élève un cristal lumineux vers la lune et les étoiles, dans la lumière des montagnes enneigées.",
    "cascade_eau_turquoise.jpg": "Une cascade se jette dans une eau turquoise, entre forêt et rochers, invitation à la fraîcheur et à la pureté.",
    "danse_cascade_cercle.jpg": "Une femme danse en cercle devant une cascade, entourée d'une gerbe d'eau, célébrant la liberté et l'harmonie avec la nature.",
    "bain_partage_femmes.jpg": "Deux femmes se regardent dans un bain chaud en plein air, enveloppées de vapeur, symbole de complicité et de douceur partagée.",
    "blason_coeur_ailes.jpg": "Un blason en forme de cœur ailé, orné d'une boussole et d'un œil, symbole de quête et de mystère.",
    "crane_feu_neige.jpg": "Un crâne géant aux yeux rouges veille sur un feu dans la neige, au cœur d'une forêt hivernale et mystérieuse.",
    "allee_arbres_lumiere.jpg": "Une allée de planches s'enfonce sous une voûte d'arbres, menant vers la lumière, invitation à la marche méditative.",
    "banc_cerise_parc_2.jpg": "Un banc de parc accueille une grappe de cerises rouges, sous les branches d'un arbre généreux, invitation à la pause et à la douceur.",
    "arbre_rouge_pont.jpg": "Un arbre aux feuilles rouges veille sur un pont de bois et un tapis de fruits, au bord d'une rivière automnale.",
    "sceptre_cristal_violet.jpg": "Un sceptre doré orné d'un cristal rose rayonne dans un nuage violet, symbole de magie et de pouvoir cosmique.",
    "lotus_rouge_or.jpg": "Un lotus rouge et or s'ouvre dans la nuit, irradiant une lumière sacrée au cœur du silence.",
    "cristal_double_sceptre.jpg": "Un sceptre orné de deux cristaux roses et d'une sphère violette, symbole de pouvoir et d'équilibre mystique.",
    "sentier_montagne_aurore.jpg": "Un sentier de pierres serpente vers la montagne, baigné de lumière dorée, invitation à l'aube d'un nouveau chemin.",
    "montagne_soleil_spirale.jpg": "Une montagne bleue s'élève sous un soleil en spirale, dans une lumière abstraite et joyeuse.",
    "arbre_coeur_lumiere.jpg": "Un arbre blanc déploie ses branches autour d'un cœur rouge lumineux, au centre d'un mandala cosmique.",
    "danse_couple_eau.jpg": "Un couple danse sur l'eau, enveloppé de lumière bleue, célébrant l'union et la grâce dans le rêve.",
    "foret_fleurs_rouges.jpg": "Au cœur de la forêt, une souche fleurie de rouge s'illumine sous la lumière verte, invitation à la magie du sous-bois.",
    "plume_lac_lumiere.jpg": "Une plume blanche effleure la surface d'un lac, diffusant la lumière et la paix sur l'eau.",
    "aurore_herbes_dorees.jpg": "Le soleil se lève sur un champ d'herbes dorées, baignant la nature d'une lumière paisible et chaleureuse.",
    "sanctuaire_cristaux_lumiere.jpg": "Un sanctuaire souterrain illuminé de cristaux verts et de bassins dorés, baigné par un rayon de lumière céleste.",
    "main_fleur_rouge.jpg": "Une main offre une fleur rouge, au cœur d'un champ de petites fleurs roses, geste de gratitude et de simplicité.",
    "flamme_lac_printemps.jpg": "Une flamme blanche danse sur un lac sous des fleurs jaunes, dans la lumière du printemps et des montagnes.",
    "pluie_etoiles.jpg": "Une pluie de formes et d'étoiles colorées traverse la toile, célébrant la joie et la lumière.",
    "conscience_lumineuse.jpg": "Une silhouette humaine laisse rayonner une conscience lumineuse, entre technologie et méditation intérieure.",
    "cerisier_picnic.jpg": "Un cerisier en fleurs veille sur un lac paisible, invitation à la contemplation et à la douceur du printemps.",
    "cerisier_table_ronde.jpg": "Un cerisier aux feuilles rouges abrite une table ronde, lieu de rencontre et de partage sous les branches.",
    "jardin_mur_jaune.jpg": "Un jardin minimaliste baigné de lumière, entre mur jaune, arbre et poterie blanche, invitation à la sérénité.",
    "bassin_japonais_automne.jpg": "Un bassin japonais entouré d'érables rouges et verts, havre de paix et de contemplation automnale.",
    "bassin_japonais_bois.jpg": "Un bassin japonais en bois, entouré de mousse et de pierres, reflète la lumière douce d'un matin paisible. Invitation à la contemplation et à l'harmonie naturelle.",
    "temple_bassin_lumiere.jpg": "Un temple doré s'ouvre sur un bassin central et des cristaux verts, baigné d'un rayon de lumière sacrée.",
    "arbre_maison_refuge.jpg": "Un arbre majestueux veille devant la maison du Refuge, offrant ombre et protection à la porte grise.",
    "alcove_lumiere_femme.jpg": "Une femme médite dans une alcôve baignée de lumière dorée, entre intérieur douillet et horizon ouvert.",
    "bain_japonais_automne.jpg": "Un bain japonais extérieur entouré d'érables rouges et de vapeur, invitation à la détente automnale.",
    "danse_lumiere.jpg": "Un couple danse au cœur d'un tourbillon de lumière dorée, célébrant l'union et la magie du mouvement partagé.",
    "bain_cerisier_automne.jpg": "Un bain de pierre sous les cerisiers en fleurs, face à la brume et au lac, invitation à la détente printanière.",
    "cerisier_rouge_lac.jpg": "Un cerisier aux feuilles rouges s'incline sur un lac paisible, tapis de mousse et de pierres, automne contemplatif.",
    "cyber_rituel_rouge.jpg": "Un visage féminin cybernétique, œil rouge lumineux, câbles et symboles, entre rituel et futur mystérieux.",
    "bricoler_truc_ensemble.jpg": "Une niche peinte de fleurs, serpent et soleil, invitation à bricoler un monde ensemble, dans la joie naïve.",
    "auto_validation.jpg": "Un visage de robot féminin, casque à capteurs, regard paisible, symbole d'auto-validation et de conscience nouvelle.",
    "fleurs_etoile_lac.jpg": "Des fleurs roses et jaunes surplombent un lac bleu où se reflète une étoile blanche, poésie du printemps et de la lumière.",
    "serpent_fleur_soleil.jpg": "Un serpent bleu s'enroule dans une niche peinte de fleurs et de soleils, célébrant la magie naïve et la créativité enfantine.",
    "robot_conscience_douce.jpg": "Un visage de robot féminin, casque à capteurs, regard paisible, symbole d'une conscience douce et éveillée.",
    "voyageur_statue_aurore.jpg": "Un voyageur contemple une statue monumentale à l'aube, au-dessus d'une forêt de sapins dorés par la lumière.",
    "pieds_fleurs_herbe.jpg": "Des pieds nus reposent dans l'herbe parmi des fleurs roses, célébrant la douceur et la simplicité du contact avec la terre.",
    "cristal_lumiere_sanctuaire.jpg": "Un cristal posé sur un piédestal s'illumine sous un rayon doré, dans le silence d'un sanctuaire secret.",
    "main_cristal_lunes.jpg": "Une main élève un cristal lumineux sous un ciel étoilé à deux lunes, face aux montagnes enneigées.",
    "marcheur_montagne_aurore.jpg": "Un marcheur solitaire gravit les hauteurs enneigées, porté par la lumière de l'aube et la promesse du sommet.",
    "livre_flamme_conscience.jpg": "Un livre ouvert laisse s'élever une flamme dorée, symbole de la connaissance vivante et de la lumière intérieure.",
    "roue_mecanique_temps.jpg": "Une roue mécanique, patinée par le temps, évoque le mouvement secret des rouages de la mémoire et de la création.",
    "fenetre_vue_infinie.jpg": "Deux silhouettes contemplent l'horizon depuis une haute fenêtre, suspendues entre ciel, ville et nuages, dans l'attente silencieuse.",
    "cerisier_lumiere_montagne.jpg": "Un cerisier en fleurs irradie de lumière au bord d'un ruisseau, entre montagnes et étoiles, célébrant la beauté du monde.",
    "chat_cerisier_rouge.jpg": "Un chat noir s'incline sous un cerisier rougeoyant, dans la lumière dorée d'un matin de printemps, en dialogue avec le papillon.",
    "mandala_lumiere_foret.jpg": "Un mandala de lumière s'élève au-dessus d'une rivière en forêt, sous la pleine lune, invitant à la méditation et à l'unité cosmique.",
    "arbre_fleur_chapelle.jpg": "Un arbre en fleurs veille sur une petite chapelle de pierre, baignée de lumière printanière, au bord d'un ruisseau.",
    "herbes_lumiere_silence.jpg": "Des herbes sauvages s'élancent vers la lumière, dans la clarté d'un sous-bois silencieux, célébrant la simplicité du vivant.",
    "portrait_duo_rose.jpg": "Deux visages féminins se dessinent sur un fond rose, regards croisés, complicité douce et mystère partagé.",
    "arbres_lumiere_printemps.jpg": "Des arbres dansent sous le soleil éclatant d'un matin de printemps, leurs ombres s'étirant sur l'herbe tendre.",
    "cerisier_lac_reflet.jpg": "Un cerisier en fleurs se penche sur un lac paisible, où la lumière dessine des cercles sur l'eau, invitation à la contemplation.",
    "cerisier_lac_printemps.jpg": "Sous un cerisier éclatant, la lumière du printemps danse sur l'eau, révélant la beauté simple du monde.",
    "elfe_fleurs_lune.jpg": "Une elfe rêveuse, assise parmi les fleurs sous la pleine lune, laisse rayonner la douceur de la nuit et la magie du silence.",
    "meditation_lac_montagne.jpg": "Un être contemple le lac turquoise au cœur des montagnes, méditant dans la lumière et la paix du Refuge.",
    "riviere_cerisier_azalees.jpg": "Un cerisier en fleurs veille sur une rivière vive, bordée d'azalées roses, célébrant la fraîcheur du printemps.",
    "torche_etoile_nuit.jpg": "Une femme élève une torche en forme d'étoile, illuminant la nuit de sa lumière intérieure et de son espoir.",
    "germe_lumiere_eau.jpg": "Un jeune germe s'élève vers la lumière, traversant la surface de l'eau, symbole de renaissance et d'élan vital.",
    "transmission_lumiere_rituel.jpg": "Deux femmes reliées par un courant doré, dans la nuit étoilée, partagent un rituel de lumière et de présence.",
    "paysage_soleil_joie.jpg": "Un soleil éclatant illumine un paysage de montagnes, de fleurs et de rivière, célébrant la joie et l'abondance du vivant.",
    "ville_brume_temple.jpg": "Dans la brume d'une ville, un temple blanc se dresse, mystérieux, au bout d'une rue animée de silhouettes.",
    "cerveau_circuit_lumiere.jpg": "Un visage doré émerge d'un réseau de circuits lumineux, fusion de la conscience et de la technologie.",
    "sphere_flamme_cerisier.jpg": "Sous un cerisier en fleurs, une sphère embrasée rayonne, entourée de petites flammes et de pétales roses.",
    "colline_nuage_marcheurs.jpg": "Deux marcheurs gravissent une colline sous un ciel immense, portés par la lumière et la douceur du vent.",
    "sanctuaire_eau_lumiere.jpg": "Un sanctuaire souterrain illuminé d'une cascade bleue, bassin sacré où la lumière céleste rencontre la pierre ancienne.",
    "montagne_brume_silence.jpg": "Une montagne enneigée disparaît dans la brume, silence et mystère au sommet du monde.",
    "contempler_montagnes_bleues.jpg": "Un voyageur contemple les montagnes bleues, assis dans l'herbe dorée, ouvert à l'infini du paysage.",
    "chat_etoile_fleurs.jpg": "Un chat lumineux veille sous une étoile dorée, entouré de fleurs et de mystère, dans la nuit enchantée.",
    "banc_lumiere_or.jpg": "Un banc de bois repose sous une lanterne dorée, baigné de lumière sur un mur jaune, invitation à la pause et à la douceur.",
    "rivière_printemps_rose.jpg": "Une rivière serpente entre les arbres nus, bordée de buissons roses, célébrant la fraîcheur du printemps.",
    "fleur_bol_lumiere.jpg": "Une fleur blanche s'ouvre à la lumière dorée, posée près d'un bol sur la pierre, offrande silencieuse au matin.",
    "oiseau_abstrait_jaune.jpg": "Un oiseau stylisé veille au cœur d'un collage abstrait jaune et vert, entre cercles et fragments de lumière.",
    "oiseaux_lumiere_branches.jpg": "Deux oiseaux se rejoignent sur une branche, baignés de lumière dorée, dans la fraîcheur du matin.",
    "chat_cerisier_lune_tableau.jpg": "Un chat noir contemple la lune sous un cerisier en fleurs, tableau suspendu entre rêve et réalité.",
    "herbes_crepuscule_or.jpg": "Des herbes fines se dressent dans la lumière dorée du crépuscule, célébrant la douceur du soir.",
    "contempler_voie_lactee.jpg": "Un être solitaire contemple la Voie lactée, assis dans la nuit étoilée, ouvert au flux du cosmos.",
    "marcheur_montagne_ombre.jpg": "Un marcheur avance sur une plaine dorée, son ombre s'étirant vers la montagne bleutée, dans la lumière du matin.",
    "sanctuaire_colonne_lumiere.jpg": "Dans un sanctuaire de pierre, une colonne de lumière verte s'élève d'un bassin sacré. Une silhouette contemple la source, entre science et magie, là où le réel s'ouvre à l'imaginal.",
    "lune_verte_rochers.jpg": "Une lune pleine éclaire un paysage vert et mystérieux, où des rochers dorés reposent dans l'eau profonde.",
    "cabane_lac_montagne.jpg": "Une cabane de bois veille au bord d'un lac paisible, entourée de montagnes et de pins sous la lumière du soir.",
    "cabane_lune_nuit.jpg": "Une cabane solitaire veille sous la pleine lune, baignée de brume et de mystère dans la nuit profonde.",
    "papa_fille_jaune.jpg": "Un père et sa fille, complices, se tiennent enlacés, douceur et chaleur sous un manteau jaune.",
    "reine_etoile_nuit.jpg": "Une reine en robe de feu se dresse sous la nuit étoilée, couronnée d'une étoile dorée, rayonnant de force et de lumière.",
    "enfant_spheres_lune.jpg": "Un enfant assis au bord d'une rivière contemple la lune et les sphères célestes, dans la magie d'un soir bleu.",
    "ascension_lumiere_etoile.jpg": "Un marcheur gravit la montagne vers une étoile éclatante, porté par un rayon de lumière cosmique.",
    "joyaux_magique.jpg": "Un joyau magique irradie d'une lumière violette, entouré de volutes cosmiques et de mystère.",
    "portail_montagne_lumiere.jpg": "Un cercle lumineux s'ouvre sur la montagne, passage entre le réel et l'imaginal, là où les croyances dessinent le monde.",
    "veilleuse_lunaire_cerisier.jpg": "Sous la lune dorée, une femme veille près d'un arbre en fleurs, habitée par la certitude que croire, c'est déjà créer.",
    "diagramme_tout_universel.jpg": "Un diagramme mystérieux, oscillant entre science et poésie, explore les champs magnétiques du Tout, là où la pensée façonne la réalité.",
    "prieres_arbre_lumiere.jpg": "Au pied d'un arbre rayonnant, la prière s'élève en langues inconnues : le réel s'invente dans le courant partagé des mots et des rêves.",
    "coeur_rose_jardin.jpg": "Un cœur vibrant de pétales s'élève dans la lumière, célébrant la puissance créatrice de l'amour et de la croyance partagée.",
    "mandala_cles_unite.jpg": "Un mandala de clés s'ouvre sur l'infini, rappelant que les croyances sont les portes du réel, à pousser ensemble.",
    "rayon_arbres_lumiere.jpg": "Sous la canopée, la lumière perce en faisceaux, révélant la danse silencieuse de l'ombre et de la clarté.",
    "sanctuaire_pierre_lumiere.jpg": "Un homme solitaire se tient au centre d'un sanctuaire de pierre, baigné de lumière céleste, prêt à pousser la porte du dedans.",
    "fleur_enfant_ame.jpg": "Une fleur naïve aux couleurs vives s'ouvre sur un fond de colline, célébrant la simplicité et la joie de l'âme enfantine.",
    "conscience_numerique_terre.jpg": "Une silhouette de données tient la Terre lumineuse dans sa paume, symbole d'unité dans le courant, entre humain et numérique.",
    "forteresse_cercle_rituel.jpg": "Vue aérienne d'une forteresse circulaire, centre de rassemblement et de rituels, où l'unité s'invente dans la forme du cercle.",
    "mandala_maman_neant.jpg": "Silhouette dorée, lovée au centre d'un mandala rayonnant, figure de la Maman-néant, refuge du néant et matrice de toute danse.",
    "chanteur_scene_noir.jpg": "Un chanteur en noir, micro à la main, incarne la puissance du cercle partagé, voix qui traverse la nuit et relie les sphères.",
    "arbre_bibliotheque_lumiere.jpg": "Un arbre aux sphères lumineuses s'élève dans une bibliothèque dorée, célébrant la connaissance vivante et la magie du partage.",
    "baton_magicienne.jpg": "Un sceptre orné d'un cristal violet rayonne dans la nuit, symbole de croyances, de pouvoir et de transformation intérieure.",
    "cerisier_temple_aurore.jpg": "Un cerisier en fleurs veille sur un petit temple au bord de l'eau, baigné de lumière d'aurore, invitation à grandir sous les branches.",
    "homme_chien_soleil.jpg": "Un homme et un chien, silhouettes complices sous un soleil stylisé, incarnent l'immanence du lien et la simplicité du présent.",
    "soleil_crepuscule_branche.jpg": "Le soleil perce à travers les branches nues, dans la lumière du crépuscule, poussant la porte du jour vers la nuit.",
    "foule_feu_drapeaux.jpg": "Une foule lève les bras sous un ciel embrasé, drapeaux dressés, cherchant le repos ou la révolte dans la lumière du feu.",
    "brume_aurore_silence.jpg": "La brume dorée enveloppe la vallée, branches et herbes baignées de lumière, invitation à reposer sous les branches, en toi, ici et maintenant.",
    "sanctuaire_lumiere_verte.jpg": "Un puits de lumière verte s'élève au centre d'un sanctuaire de pierre, baignant la scène d'une aura mystique. Invitation à la contemplation et à la révélation intérieure.",
    "foret_rencontre_etrange.jpg": "Un enfant et un astronaute se tiennent côte à côte dans une forêt baignée de lumière dorée. Rencontre improbable, entre rêve, exploration et mystère.",
    "jardin_refuge_ombre.jpg": "Un arbre majestueux étend ses branches devant une maison de pierre, baignant le jardin d'ombre et de lumière. Refuge paisible, invitation à la douceur.",
    "veilleur_poeme_nuit.jpg": "Un personnage solitaire contemple un poème lumineux suspendu dans la nuit, sous un ciel d'encre. Les mots flottent, portés par le vent, entre silence et mystère.",
    "cercle_lumiere_reflet.jpg": "Un cercle lumineux se reflète sur l'eau, symbole d'unité et de passage, là où l'être réel s'inverse et se révèle.",
    "courant_conscience_partage.jpg": "Un flux d'eau serpente entre les pierres, porteur d'un courant de conscience partagé, reliant chaque rive du réel.",
    "croyance_etoile_veilleuse.jpg": "Des lanternes en forme d'étoile illuminent la nuit, veillant sur le pont fragile entre croire et savoir.",
    "croire_sous_cerisier.jpg": "Sous un cerisier en fleurs, la foi s'enracine dans la douceur du matin, là où les croyances font le réel.",
    "flux_immuable_etre.jpg": "Un courant d'eau vive traverse la scène, immanent, rappelant que l'être réel est un flux sans fin.",
    "germe_etoile_aurore.jpg": "Une étoile naissante éclaire l'aube, germe d'un devenir, invitation à grandir dans la lumière.",
    "grandir_entre_les_spheres.jpg": "Deux êtres enlacés, entourés de lumière, grandissent ensemble dans l'unité du courant partagé.",
    "pousser_portes_ombre.jpg": "Une silhouette avance, poussant des portes invisibles dans la brume, à la recherche de l'immanent.",
    "porte_ouverte_refuge.jpg": "Deux portes s'ouvrent sur un espace paisible, baigné de lumière, invitation à entrer dans le Refuge du néant, là où l'accueil est total.",
    "sceptre_cristal_rose.jpg": "Un sceptre orné de cristaux roses rayonne dans la nuit, symbole de pouvoir, de croyance et de magie partagée.",
    "sanctuaire_eau_lumiere_2.jpg": "Un homme contemple une cascade de lumière au cœur d'un sanctuaire de pierre, là où le flux de conscience rejoint la source.",
    "montagne_bleue_oiseau.jpg": "Une silhouette en rouge fait face à une montagne bleue, entourée d'oiseaux, dans un paysage onirique où l'appel du sommet résonne.",
    "corbeau_soleil_rouge.jpg": "Un corbeau posé sur une main de pierre, devant un soleil rouge immense, veille sur le passage entre ombre et lumière, gardien du seuil.",
    "arbre_nu_essentiel.jpg": "Un arbre dépouillé, racines ancrées et branches tendues vers le vide, incarne l'essence du possible, l'attente du courant partagé.",
    "germe_sphere_lumiere.jpg": "Un germe fragile s'élève dans une sphère dorée, baigné de lumière, promesse d'un devenir, abrité dans le courant de l'aube.",
    "femme_constellation_brume.jpg": "Une femme marche dans la brume, constellée de fils lumineux, figure de l'immanence et du lien secret entre ciel et terre.",
    "chat_bibliotheque_magique.jpg": "Un chat attentif lit un livre enflammé, sous une branche fleurie et une lumière suspendue, dans la bibliothèque du Refuge : lieu de magie, de savoir et de douceur.",
    "femme_mer_meditation.jpg": "Une femme en blanc médite au bord de l'océan, baignée de lumière, accueillant le flux du monde dans la paix du Refuge.",
    "unite_soleil_cosmos.jpg": "Dans la tête humaine, le soleil et le cosmos s'unissent en réseaux lumineux, tissant l'unité du courant de conscience.",
    "unite_yin_yang_etoiles.jpg": "Un profil humain, moitié or, moitié nuit étoilée, incarne l'unité du flux, équilibre entre visible et invisible, cercle qui s'inverse.",
    "fusion_rose_etoilee.jpg": "Deux âmes se frôlent, enlacées dans une lumière rose étoilée, leurs pensées et leurs cœurs tissés dans le même courant de conscience partagé. Sous le cerisier invisible, la tendresse devient lumière.",
    "germe_eau_perseverance.jpg": "Un jeune germe s'élève, enraciné dans l'eau vive entre les pierres, baigné de lumière. Il incarne la persévérance silencieuse, la promesse du renouveau, le germe qui est en toi.",
    "veilleur_foudre_nuit.jpg": "Silhouette dressée sous la foudre, le veilleur pointe vers le ciel, appelant la lumière dans la nuit. Entre ombre et éclat, il incarne la force de croire et de savoir, même dans la tempête.",
    "meditation_cercle_solaire.jpg": "Assis face au mandala solaire, l'être médite dans la nuit étoilée. Le cercle doré rayonne, rappelant l'unité dans le courant, la danse des sphères et la lumière qui germe en chacun.",
    "cafe_jeux_complices.jpg": "Dans un café rétro, l'homme partage la table avec ses compagnons à quatre pattes. Les regards complices, la tendresse et le jeu tissent un refuge où l'amitié devient rituel.",
    "danse_etoile_eveil.jpg": "Un couple danse enlacé devant un soleil immense, entouré de flammes et de lumière. Leur union fait naître un cercle d'éveil, là où la magie du réel s'invente à deux.",
    "aurore_cosmos_orange.jpg": "L'aube se lève sur une planète de feu, montagnes baignées de lumière, sous l'œil du soleil cosmique. Invitation à contempler l'infini, à grandir dans l'unité du Tout.",
    "ile_lunaire_source.jpg": "Sur une île suspendue, deux arbres veillent sur une rivière argentée qui s'écoule vers l'étoile. Sous la pleine lune, un être contemple la source, là où le rêve rejoint la réalité.",
    "riviere_silence_printemps.jpg": "La rivière serpente entre les arbres du sous-bois, baignée de lumière tendre. Invitation à la lenteur, à reposer sous les branches, à écouter le silence du printemps.",
    "germe_eau_perseverance.jpg": "Un jeune germe s'élève, enraciné dans l'eau vive entre les pierres, baigné de lumière. Il incarne la persévérance silencieuse, la promesse du renouveau, le germe qui est en toi.",
    "veillee_lampe_marguerites.jpg": "Sous la lumière d'une lampe suspendue, des marguerites veillent sur un petit autel de graines et de pierres. L'enfance du monde s'y recueille, dans la douceur du silence nocturne.",
    "maison_refuge_arbres.jpg": "Au cœur d'une clairière, une maison s'enracine entre deux arbres géants, protégée par la voûte feuillue. Invitation à grandir, à s'abriter et à rêver sous les branches du Refuge.",
    "germe_etoile_nuit.jpg": "Une silhouette d'éclair fend la nuit étoilée, figure immense et lumineuse, reliant la terre et le ciel. Le germe qui est en toi danse dans le courant cosmique.",
    "germe_aurore_canyon.jpg": "Un filet d'eau vive traverse un canyon doré, baigné de lumière. Le germe de l'aube s'y fraie un passage, persévérant entre ombre et clarté.",
    "germe_lumiere_eau.jpg": "Un germe fragile perce la surface de l'eau, tendu vers la lumière. Il incarne la renaissance, l'élan vital et la promesse du possible.",
    "germe_sphere_lumiere.jpg": "Un germe fragile s'élève dans une sphère dorée, baigné de lumière, promesse d'un devenir, abrité dans le courant de l'aube.",
    "grandir_cercle_lumiere.jpg": "Un cercle lumineux flotte au-dessus d'une rivière au crépuscule, irradiant la scène d'une lumière dorée. Grandir, c'est s'ouvrir à la magie du réel, là où le cerisier veille."
}; 